### ISSUE TITLE
Extend to 4 fingers and add swipe direction checks

### ISSUE THREAD

**Issue by kprinssu** [Exalm/gnome-shell-extension-workspace-switch-gesture#7]
Three feature requests:

- simply changing https://github.com/Exalm/gnome-shell-extension-workspace-switch-gesture/blob/master/workspace_switch_gesture%40exalm/gesture.js#L28 to a `!= 4` doesn't to do the trick, looks libinput or Gnome overrides the gesture

- using 3 finger swipes in any direction causes to move the workspace, would it not be more natural to only do it for up/down swipes

- if the gesture is more than half way complete, it would feel a bit more natural to have the workspace complete the siwtch (similar to macOS and Win10)

**Comment by Exalm** [comment]
1. It does. There's a default 4-finger gesture that does the same thing as this one, just without animation. So what's the request?
2. No, because this also works when workspaces are horizontal.
3. Doesn't it already do this? This is probably a bug.

**Comment by kprinssu** [comment]
These are small gripes I found and appreciate the effort you put into the extension! I don’t mean come off as rude. The above were small gripes I found:

Would it not be possible to override the built in Gnome 4 finger gestures? The animation provided by your extension  is much better than the default Gnome action.
 
Do you think it will be better to have a configuration setting to have it work for horizontal, vecttia, or both? It feels slightly unnatural having it work in any gesture direction (e.g. trying to do a 3 finger swipe left, unintenionally causes the workspace animation to kick in).

I will create a gif showing the switch not completing.

**Comment by Exalm** [comment]
Umm, I don't know why you thought you came off as rude.
It is possible to override it. I didn't do that because my touchpad only supports 3 fingers. :/ I didn't really mean for this as for a "real" extension, that's why it's not on extensions.gnome.org, unlike Dynamic Battery, and there's no configuration.
The problem with configuring vertical/horizontal swipes separately is: what if I have horizontal workspaces and only vertical swipe, or vice versa? It just wouldn't work and would be broken.
But I agree that it conflicts with 3-finger swipe gesture (in Builder, I think?), and I don't really know what to do about this.

**Comment by kprinssu** [comment]
Changing those constants did the trick. YMMV, but I increased `SPEED_FACTOR_Y` to 5.0. I am going to close this issue.
